grpc:
  server:
    port: 9898

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: simple

logging:
  level:
    root: INFO
#    web: DEBUG

spring.threads.virtual.enabled: false